name: alertmanager
category: monitoring
description: Handles alerts from Prometheus and routes them to receivers such as email or Slack
repoURL: https://prometheus-community.github.io/helm-charts
chart: alertmanager
targetRevision: "1.33.1"
namespace: monitoring
enabled: false
